repos:
  - repo: local

    hooks:
      - id: mypy
        name: mypy
        entry: python -m mypy src/
        language: python  
        types: [python]
        pass_filenames: false  
        always_run: true  
        additional_dependencies: [mypy]

      - id: ruff
        name: ruff
        entry: python -m ruff check .
        language: python  
        types: [python]
        pass_filenames: true
        always_run: true
        additional_dependencies: [ruff]
