repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy src/
        language: system
        pass_filenames: true

      - id: ruff
        name: ruff
        entry: ruff check .
        language: system
        pass_filenames: true
