repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: python -m mypy src/
        language: python
        types: [python]
        pass_filenames: false

      - id: ruff
        name: ruff
        entry: python -m ruff check .
        language: python
        types: [python]
        pass_filenames: true
