services:
  rabbitmq:
    image: rabbitmq:3-management  # Версия с веб-интерфейсом
    ports:
      - "5672:5672"  # AMQP (для клиентов)
      - "15672:15672"  # Веб-интерфейс (логин: guest/guest)
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=blabla
      - POSTGRES_DB=user_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  rabbitmq_data:
  postgres_data: