"""add tables

Revision ID: f6328740ca30
Revises: 
Create Date: 2025-07-29 01:09:56.104062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6328740ca30'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicants',
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('direction_code', sa.String(), nullable=False),
    sa.Column('reception', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('submit', sa.String(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('entrance_exam_points', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('additional_points', sa.Integer(), nullable=False),
    sa.Column('without_entrance_exams', sa.Boolean(), nullable=False),
    sa.Column('advantage', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('university_id', 'id', 'direction_code', name='applicant_pk')
    )
    op.create_table('directions',
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('education_form', sa.String(), nullable=False),
    sa.Column('institute', sa.String(), nullable=True),
    sa.Column('budget_places', sa.Integer(), nullable=False),
    sa.Column('total_places', sa.Integer(), nullable=False),
    sa.Column('education_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('university_id', 'code', name='direction_pk')
    )
    op.create_table('universitys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('universitys')
    op.drop_table('directions')
    op.drop_table('applicants')
    # ### end Alembic commands ###
